# 🔢 Álgebra Linear com NumPy

Este notebook demonstra como utilizar o **NumPy** para resolver problemas comuns de **álgebra linear**, como multiplicação de matrizes, sistemas de equações e decomposições.

---

## 📌 Conteúdo
1. Criação de matrizes
2. Multiplicação de matrizes
3. Transposição e inversa
4. Determinante
5. Autovalores e autovetores
6. Resolução de sistemas lineares

---

## 🚀 Importando o NumPy

In [9]:
import numpy as np

## 1️⃣ Criando matrizes

In [2]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

print("Matriz A:\n", A)
print("Matriz B:\n", B)


Matriz A:
 [[1 2]
 [3 4]]
Matriz B:
 [[5 6]
 [7 8]]


## 2️⃣ Multiplicação de matrizes

In [3]:
# Produto matricial
print("A x B:\n", np.dot(A, B))

# Multiplicação elemento a elemento
print("A * B:\n", A * B)


A x B:
 [[19 22]
 [43 50]]
A * B:
 [[ 5 12]
 [21 32]]


## 3️⃣ Transposição e inversa

In [4]:
print("Transposta de A:\n", A.T)

# Inversa de A
A_inv = np.linalg.inv(A)
print("Inversa de A:\n", A_inv)

# Verificação: A * A_inv ≈ Identidade
print("A x A_inv:\n", np.dot(A, A_inv))


Transposta de A:
 [[1 3]
 [2 4]]
Inversa de A:
 [[-2.   1. ]
 [ 1.5 -0.5]]
A x A_inv:
 [[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


## 4️⃣ Determinante

In [5]:
det_A = np.linalg.det(A)
print("Determinante de A:", det_A)


Determinante de A: -2.0000000000000004


## 5️⃣ Autovalores e autovetores

In [6]:
eigvals, eigvecs = np.linalg.eig(A)
print("Autovalores:", eigvals)
print("Autovetores:\n", eigvecs)


Autovalores: [-0.37228132  5.37228132]
Autovetores:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


## 6️⃣ Resolvendo sistemas lineares

Exemplo:  
Resolver o sistema   
2x + y = 5  
x - y = 1

In [13]:


# Coeficientes do sistema
coef = np.array([[2, 1], [1, -1]])
const = np.array([5, 1])

# Solução do sistema
solucao = np.linalg.solve(coef, const)
print("Solução do sistema:", solucao)



Solução do sistema: [2. 1.]
