# 📘 Introdução ao NumPy

O **NumPy** é a biblioteca fundamental para computação numérica em Python.  
Ele fornece suporte para **arrays multidimensionais**, além de funções matemáticas e estatísticas otimizadas.  

Neste notebook, veremos os conceitos básicos:

- Criação de arrays
- Indexação e slicing
- Tipos de dados (`dtype`)
- Operações elementares

---

## 1. Importando o NumPy

In [1]:
import numpy as np

print("Versão do NumPy:", np.__version__)

Versão do NumPy: 1.26.4


## 2. Criação de Arrays

O NumPy oferece diversas formas de criar arrays.

In [2]:
# A partir de uma lista
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# Arrays multidimensionais
matriz = np.array([[1, 2, 3], [4, 5, 6]])
print(matriz)

# Funções de criação
zeros = np.zeros((3, 3))      # Matriz 3x3 de zeros
uns = np.ones((2, 4))         # Matriz 2x4 de uns
sequencia = np.arange(0, 10)  # Sequência de 0 a 9
espacado = np.linspace(0, 1, 5)  # 5 valores entre 0 e 1
print(espacado)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
[0.   0.25 0.5  0.75 1.  ]


## 3. Indexação e Slicing

Acessando e manipulando elementos dos arrays.

In [3]:
arr = np.array([10, 20, 30, 40, 50])

print("Elemento na posição 0:", arr[0])   # Primeiro elemento
print("Último elemento:", arr[-1])       # Último elemento
print("Slice do 1 ao 3:", arr[1:4])      # Fatia (do índice 1 até 3)

# Arrays multidimensionais
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Elemento linha 1, coluna 2:", matriz[1, 2])
print("Segunda linha inteira:", matriz[1, :])
print("Terceira coluna inteira:", matriz[:, 2])


Elemento na posição 0: 10
Último elemento: 50
Slice do 1 ao 3: [20 30 40]
Elemento linha 1, coluna 2: 6
Segunda linha inteira: [4 5 6]
Terceira coluna inteira: [3 6 9]


## 4. Tipos de Dados (dtype)

Cada array NumPy tem um tipo de dado definido.

In [4]:
arr_int = np.array([1, 2, 3], dtype=np.int32)
arr_float = np.array([1.5, 2.7, 3.9], dtype=np.float64)

print("arr_int:", arr_int, "| dtype:", arr_int.dtype)
print("arr_float:", arr_float, "| dtype:", arr_float.dtype)

# Conversão de tipos
arr_convertido = arr_int.astype(np.float64)
print("Convertido para float:", arr_convertido, "| dtype:", arr_convertido.dtype)


arr_int: [1 2 3] | dtype: int32
arr_float: [1.5 2.7 3.9] | dtype: float64
Convertido para float: [1. 2. 3.] | dtype: float64


## 5. Operações Elementares

NumPy permite operações vetorizadas rápidas.

In [5]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("Soma:", a + b)
print("Subtração:", b - a)
print("Multiplicação:", a * 2)
print("Divisão:", b / a)
print("Potenciação:", a ** 2)


Soma: [11 22 33 44 55]
Subtração: [ 9 18 27 36 45]
Multiplicação: [ 2  4  6  8 10]
Divisão: [10. 10. 10. 10. 10.]
Potenciação: [ 1  4  9 16 25]


## 🎯 Conclusão

Neste notebook aprendemos os conceitos básicos do NumPy:  
- Criação de arrays  
- Indexação e slicing  
- Tipos de dados (dtype)  
- Operações vetorizadas  
Esses fundamentos são a base para explorar recursos mais avançados como **álgebra linear**, **broadcasting** e **manipulação de memória.**