# 📌 Broadcasting e Casos Especiais em NumPy

## 1️⃣ Introdução ao Broadcasting
Broadcasting é um mecanismo do NumPy que permite operações entre arrays de tamanhos diferentes, sem a necessidade de replicação explícita dos dados.

Regras do Broadcasting
- Dimensões iguais ou uma delas é 1.  
- Se os tamanhos não coincidem, o array com tamanho 1 é "esticado".  
- Se nenhum dos tamanhos for 1 → Erro!
-  
## 2️⃣ Exemplos Práticos 
#### 🔹 Exemplo 1: Soma com Escalar

In [4]:
import numpy as np

a = np.array([1, 2, 3])
b = 5  
print(a + b)  # Broadcasting: [6, 7, 8]

# saida dever ser [6 7 8]

[6 7 8]


#### 🔹 Exemplo 2: Array (3,) + (3, 1)

In [5]:
a = np.array([1, 2, 3])      # Shape (3,)
b = np.array([[1], [2], [3]]) # Shape (3, 1)
print(a + b)



[[2 3 4]
 [3 4 5]
 [4 5 6]]



saída:  
[[2 3 4]  
 [3 4 5]  
 [4 5 6]]  
  
Explicação:  
- `a` (3,) → (1, 3) → (3, 3) (broadcasted)  
- `b` (3,1) → (3, 3) (broadcasted)



#### 🔸 Exemplo 3: Caso Especial (Erro de Broadcasting)

In [6]:
a = np.array([1, 2, 3])  # (3,)
b = np.array([1, 2])      # (2,)
try:
    print(a + b)  # Falha! (3 ≠ 2)
except ValueError as e:
    print("Erro:", e)

Erro: operands could not be broadcast together with shapes (3,) (2,) 


Saída:  
Erro: operands could not be broadcast together with shapes (3,) (2,)

## 3️⃣ Aplicação Prática: Normalização de Dados

In [7]:
data = np.random.rand(5, 3)  # 5 amostras, 3 features
mean = data.mean(axis=0)     # Média por coluna (shape (3,))
std = data.std(axis=0)       # Desvio padrão (shape (3,))

normalized = (data - mean) / std  # Broadcasting!
print(normalized)

[[-1.12385973 -0.37633025 -0.51207098]
 [-0.59572742  1.17920304 -1.62902853]
 [ 0.79192269 -0.76242388  0.2712388 ]
 [-0.61427395 -1.22142126  0.57279135]
 [ 1.54193842  1.18097234  1.29706936]]


Funciona porque:  
- `data` tem shape `(5, 3)`  
- `mean` e `std` têm shape `(3,)` → automaticamente ajustados para `(1, 3)` → `(5, 3)`.

## 4️⃣ Casos Especiais Avançados
#### 🔺 Adicionando Dimensões com `np.newaxis`

In [8]:
a = np.array([1, 2, 3])  # Shape (3,)
a_col = a[:, np.newaxis] # Shape (3, 1)
print(a_col)

[[1]
 [2]
 [3]]


##### Saída:  
[[1]  
 [2]  
 [3]]  

#### 🔻 Broadcasting em Operações com Matrizes

In [9]:
A = np.array([[1, 2], [3, 4]])  # (2, 2)
v = np.array([10, 20])          # (2,)
print(A * v)  # Multiplicação elemento a elemento (broadcasting)

[[10 40]
 [30 80]]


#### Saída:  
[[10 40]  
 [30 80]]

## 5️⃣ Resumo
✔ Broadcasting permite operações entre arrays de shapes diferentes.  
✔ Funciona quando as dimensões são compatíveis (iguais ou 1).  
✔ Muito útil em normalização, álgebra linear e machine learning!  