# ⚡ Funções Avançadas no NumPy

Este notebook apresenta **funcionalidades avançadas do NumPy**, indo além das operações básicas e de álgebra linear.  
O objetivo é demonstrar como explorar **funções universais (ufuncs)**, **broadcasting**, agregações e estatísticas, úteis em projetos de **Ciência de Dados**.

---

## 📌 Conteúdo
1. Funções universais (ufuncs)
2. Broadcasting
3. Estatísticas descritivas
4. Funções matemáticas avançadas
5. Agregações em eixos
6. Ordenação e seleção

---

### 🚀 Importando o NumPy

In [3]:
import numpy as np

## 1️⃣ Funções universais (ufuncs)

São operações **vetorizadas** aplicadas em arrays, muito mais rápidas que loops em Python.

In [4]:
x = np.array([1, 2, 3, 4, 5])

print("Quadrado:", np.square(x))
print("Raiz quadrada:", np.sqrt(x))
print("Exponencial:", np.exp(x))
print("Logaritmo natural:", np.log(x))


Quadrado: [ 1  4  9 16 25]
Raiz quadrada: [1.         1.41421356 1.73205081 2.         2.23606798]
Exponencial: [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
Logaritmo natural: [0.         0.69314718 1.09861229 1.38629436 1.60943791]


## 2️⃣ Broadcasting  
Permite operações entre arrays de dimensões diferentes.

In [5]:
A = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print("Array A:\n", A)
print("Array b:\n", b)

# Broadcasting adiciona b a cada linha de A
print("A + b:\n", A + b)


Array A:
 [[1 2 3]
 [4 5 6]]
Array b:
 [10 20 30]
A + b:
 [[11 22 33]
 [14 25 36]]


## 3️⃣ Estatísticas descritivas

In [6]:
dados = np.random.randn(1000)  # 1000 números aleatórios (distribuição normal)

print("Média:", np.mean(dados))
print("Mediana:", np.median(dados))
print("Desvio padrão:", np.std(dados))
print("Mínimo:", np.min(dados))
print("Máximo:", np.max(dados))


Média: -0.009535102971162552
Mediana: -0.02814630881328039
Desvio padrão: 0.9822369050260789
Mínimo: -3.016449098392563
Máximo: 3.9496882427825173


## 4️⃣ Funções matemáticas avançadas

In [7]:
angulos = np.linspace(0, np.pi, 5)

print("Seno:", np.sin(angulos))
print("Cosseno:", np.cos(angulos))
print("Tangente:", np.tan(angulos))


Seno: [0.00000000e+00 7.07106781e-01 1.00000000e+00 7.07106781e-01
 1.22464680e-16]
Cosseno: [ 1.00000000e+00  7.07106781e-01  6.12323400e-17 -7.07106781e-01
 -1.00000000e+00]
Tangente: [ 0.00000000e+00  1.00000000e+00  1.63312394e+16 -1.00000000e+00
 -1.22464680e-16]


## 5️⃣ Agregações em eixos

In [8]:
M = np.array([[1, 2, 3], [4, 5, 6]])

print("Soma total:", np.sum(M))
print("Soma por linha:", np.sum(M, axis=1))
print("Soma por coluna:", np.sum(M, axis=0))


Soma total: 21
Soma por linha: [ 6 15]
Soma por coluna: [5 7 9]


## 6️⃣ Ordenação e seleção

In [9]:
valores = np.array([7, 2, 9, 4, 1])

print("Array original:", valores)
print("Ordenado:", np.sort(valores))
print("Índices ordenados:", np.argsort(valores))

# Selecionando os 3 maiores valores
indices = np.argsort(valores)[-3:]
print("Top 3 valores:", valores[indices])


Array original: [7 2 9 4 1]
Ordenado: [1 2 4 7 9]
Índices ordenados: [4 1 3 0 2]
Top 3 valores: [4 7 9]


✅ Este notebook mostra **habilidades avançadas com NumPy**, incluindo estatísticas, funções matemáticas e técnicas de manipulação eficientes, muito usadas em **Ciência de Dados e Machine Learning**.
